name: Test
description: |
  Run clippy, tests, and doc tests on pushes or PRs.

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          override: true

      - name: Install dev tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack@0.6

      - name: Run tests
        run: |
          make check
          make test
